### ISSUE TITLE
Avoid using web-only libraries outside Flutter web plugin packages.

### ISSUE THREAD

**Issue by piggychu0w0** [cyclone-pk/pythonandflutter#2]
Hi, I met a problem as I tap the search button. The 'Query' word doesn't change, and it shows it shows the wrong message.
`Avoid using web-only libraries outside Flutter web plugin packages.`
How should I solve it?

[Here is my code.](https://github.com/piggychu0w0/flutter-python)
Thanks a lot for your help.

**Comment by piggychu0w0** [comment]
After that I fix all the problem but it still stops at getdata with no error.
I don't have any thought about it, what should I do?

**Comment by cyclone-pk** [comment]
how you produce the the error
